### PR TITLE
initial commit of ref app

### PR DESCRIPTION
**Pull request by joellecurcioSAP**

### CODE REVIEW

**Review by marco-porru — COMMENTED** [review]
is it required the IoT_Edge/persistence-service-ref-app/.idea folder? if not could you remove it?

**Review by marco-porru — COMMENTED** [review]
please also exclude from commit also the .DS_Store file

**Review by marco-porru — COMMENTED** [review]
please remove also IoT_Edge/persistence-service-ref-app/app/.DS_Store

**Review by marco-porru — CHANGES_REQUESTED** [review]
in the app folder you probably would like to remove the log folder too

**Review by marco-porru — CHANGES_REQUESTED** [review]
please do not include "target" folder

**Review by marco-porru — APPROVED** [review]

**Comment by joellecurcioSAP** [comment]
Adding persistence service reference application

**Pull request merged**
